Neos:
  Flow:
    resource:
      targets:
        localWebDirectoryPersistentResourcesTarget:
          target: 'PunktDe\OutOfBandRendering\ResourceManagement\CommandRequestAwareFileSystemSymlinkTarget'
